name: Sync to Personal Private Repo

on:
  push:
    branches:
      - main
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'Sarang-Univ/sarang-univ-retreat-web'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add personal repo as remote
        run: |
          git remote add personal git@github.com:sarang-univ-dev/sarang-univ-retreat-web.git

      - name: Verify Remote URLs
        run: git remote -v

      - name: Create and sync with personal account
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}

          # 원격 저장소의 파일들 가져오기
          mkdir -p /tmp/sarang-repo-content
          cp -r * /tmp/sarang-repo-content/ 2>/dev/null || true
          cp -r .* /tmp/sarang-repo-content/ 2>/dev/null || true

          # 임시 브랜치 생성
          git checkout --orphan temp-branch

          # 기존 파일 정리 및 백업 파일 복원
          git rm -rf . --quiet
          cp -r /tmp/sarang-repo-content/* . 2>/dev/null || true
          cp -r /tmp/sarang-repo-content/.* . 2>/dev/null || true

          # personal 계정으로 설정
          git config user.name "sarang-univ-dev"
          git config user.email "sarang-univ-dev@users.noreply.github.com"

          # 모든 파일 추가 및 커밋
          git add -A
          git commit -m "Sync from Sarang-Univ repository (${BRANCH} branch)"

          # personal 저장소로 강제 푸시
          git push personal temp-branch:$BRANCH --force
