name: Sync to Personal Private Repo

on:
  push:
    branches:
      - main
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'Sarang-Univ/sarang-univ-retreat-web'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add personal repo as remote
        run: |
          git remote add personal git@github.com:sarang-univ-dev/sarang-univ-retreat-web.git

      - name: Verify Remote URLs
        run: git remote -v

      - name: Create single commit with personal account
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}

          # 임시 브랜치 생성
          git checkout -b temp-branch

          # personal 계정으로 설정
          git config user.name "sarang-univ-dev"
          git config user.email "sarang-univ-dev@users.noreply.github.com"

          # 모든 파일 초기화 후 커밋
          git rm -rf .
          git checkout $BRANCH -- .
          git add .
          git commit -m "Sync from Sarang-Univ repository"

          # personal 저장소로 강제 푸시
          git push personal temp-branch:$BRANCH --force
